### ISSUE TITLE
侧滑返回缺失

### ISSUE THREAD

**Issue by popor** [HDB-Li/LLDebugTool#1]
1.如题

**Comment by HDB-Li** [comment]
请描述一下出现或者复现这个问题的步骤，最好包括出现问题的机型，系统版本和XCode版本。😃

**Comment by popor** [comment]
iPhone6plus,系统版本号是11.3.1, xcode是9.3.
弹出LLDebug界面,push一个vc之后,侧滑屏幕边界返回的事件是缺失的.
不知道是不是没有设置self.interactivePopGestureRecognizer.delegate = (id<UIGestureRecognizerDelegate>)self;
