### ISSUE TITLE
使用过程中几个问题

### ISSUE THREAD

**Issue by JDongKhan** [HDB-Li/LLDebugTool#13]
因集成进APP有很多问题，现在我们是直接以源码的方式引进并做了很多修改

修改点如下：
1、LLBaseViewController setUpTableView里面需要添加
self.tableView.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;
2、所有的image读取方法应该使用bundle（包括xib）         
  UIImage *image = [UIImage imageNamed:imageName inBundle:[NSBundle bundleForClass:[self class]] compatibleWithTraitCollection:nil];
3、网络和日志删除需要在子线程操作
4、LLWindowViewController在iOS9以下会导致主APP状态栏消失，在里面添加preferredStatusBarStyle方法即可
5、LL_defaultSessionConfiguration方法里面的NSURLSessionConfiguration注册LLURLProtocol在低版本如iOS8.1会导致请求失败
6、LLLogVC里面的        
self.filterView = [[LLFilterView alloc] initWithFrame:CGRectMake(0, LL_NAVIGATION_HEIGHT, LL_SCREEN_WIDTH, 40)];
应改成
        self.filterView = [[LLFilterView alloc] initWithFrame:CGRectMake(0, 0, LL_SCREEN_WIDTH, 40)];

我们还有一些需求，希望能实现
需求：
1、网络UI可以过滤查询
2、LLConfig需要增加appIdentity标识APP，将所有文件操作的在appIdentity目录下，这样可以定制存储目录

**Comment by HDB-Li** [comment]
Thank you for your comments. The second opinion has been fixed in `Version 1.1.1`. I will release a new version after fix other problems. Hope You can merge back to your branch at that time.

**Comment by HDB-Li** [comment]
Hi, I have a question about Question 6.  Did U use runtime to set `navigationBar.translucent` to NO, Such as `self.navigationController.navigationBar.translucent = NO;`

**Comment by JDongKhan** [comment]
@HDB-Li 多谢，如果能在fps过低能记录所有线程的堆栈最好了！

**Comment by HDB-Li** [comment]
It's a good idea. I will try to do it.

**Comment by JDongKhan** [comment]
@HDB-Li 上面第四条还是有问题，我加入
- (BOOL)prefersStatusBarHidden {
    return NO;
}

就好了，很奇怪的问题，上层的window居然会影响到下面的window的状态栏

**Comment by JDongKhan** [comment]
@HDB-Li 还有 LLStorageManager 这个类应该所有操作都要在子线程，目前删除大量数据数会卡死好久
