### ISSUE TITLE
signal 6 exception

### ISSUE THREAD

**Issue by JDongKhan** [HDB-Li/LLDebugTool#16]
在saveCrashModel加入下面的方法，会出现保存不了的问题，还会连环出现好几次的signal 6 exception
  if ([NSThread currentThread] == [NSThread mainThread]) {
      dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            [self saveCrashModel:model];
        });
        return YES;
    }

注掉就没问题了，可在SignalHandler里面加个alert调试。

**Comment by JDongKhan** [comment]
还有希望LLWindowViewController 支持tabbar重写，我们可能不需要crash，而加入自己的网络切换模块！

**Comment by HDB-Li** [comment]
@JDongKhan   
This is a fucking code I write.   A crash is a fast situation, and you should not save the model with background threads, or the program will end before saving it.  I modified `LLAppHelper` to make sure that method `subviews` was called in the main thread. You can see what I do in [63a82e9](https://github.com/HDB-Li/LLDebugTool/commit/f567f445f114e3692efbbf64a6620b99288ff16f) commit. I will merge to master when I finish modification of `LLStorageManager`.  About customized tabbar, I didn't have some good ideal. sorry.

**Comment by JDongKhan** [comment]
@HDB-Li  还有麻烦把keyWindow改为delegate.window，keyWindow可能会变！

**Comment by HDB-Li** [comment]
@JDongKhan  Hi I have already refactory database, and convert keyWindow to delegate.window. Try to upgrade it.   But I didn't had a idea to customized tabbar, I had put this issue in [Backlog](https://github.com/HDB-Li/LLDebugTool/projects/2) and will fix it in future.😆

**Comment by JDongKhan** [comment]
好的多谢，不好意思又发现个问题，就是LLNetworkModel里面的headerFields能否改成copy，我们在使用过程中总是挂在LLURLProtocol的stoploading方法的headerFields获取上
