### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pcccccc** [HDB-Li/LLDebugTool#18]
您好，当我使用AFNetworking下载文件时，调用了LLDebugTool的LLNetworkingModel调用了headerString的get方法，[LLTool convertJSONStringFromDictionary:self.headerFields]方法执行，
这时self.headerFields为空，程序崩溃。

**Comment by HDB-Li** [comment]
@pcccccc  I will fix this bug in version 1.1.3 tonight or tomorrow. Thanks  😆

**Comment by HDB-Li** [comment]
@pcccccc  All ready fix in [Version 1.1.3](https://github.com/HDB-Li/LLDebugTool/releases/tag/1.1.3). try to upgrade it.
