### ISSUE TITLE
run error with swift

### ISSUE THREAD

**Issue by MIyulong** [HDB-Li/LLDebugTool#22]
1. don't use to debug model，“pod 'LLDebugTool' ,:configurations => ['Debug']”
2. database initialized error
![image](https://user-images.githubusercontent.com/8175565/44261084-172df400-a249-11e8-9e21-4c1d1f2aaffd.png)

**Comment by HDB-Li** [comment]
Upgrade to version 1.1.3.   I had fix this problem. 😆

**Comment by MIyulong** [comment]
so cool, i get it...😈
