### ISSUE TITLE
image为nil null崩溃

### ISSUE THREAD

**Issue by zou145688zhuang** [HDB-Li/LLDebugTool#24]
做一下安全判断
if (image && image !=nil && ![image isEqual:[NSNull class]]){
                [UIPasteboard generalPasteboard].image = image;
                [self toastMessage:[NSString stringWithFormat:@"Copy \"%@\" Success",title]];
            }

**Comment by HDB-Li** [comment]
@zou145688zhuang  OK I will fix it and make a safer judgment , Thanks. 

One more question, How did you make `[UIImage imageWithData:obj]` return a NSNull object?

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    NSString *title = self.titleArray[indexPath.row];
    if ([self.canCopyArray containsObject:title]) {
        id obj = self.contentArray[indexPath.row];
        if ([obj isKindOfClass:[NSData class]] && self.model.isImage) {
            UIImage *image = [UIImage imageWithData:obj];
            [UIPasteboard generalPasteboard].image = image;
        } else {
            if ([obj isKindOfClass:[NSData class]]) {
                obj = [self convertDataToHexStr:obj];
            }
            [UIPasteboard generalPasteboard].string = obj;
        }
        [self toastMessage:[NSString stringWithFormat:@"Copy \"%@\" Success",title]];
    }

}
```

**Comment by zou145688zhuang** [comment]
![2018-08-21 2 36 36](https://user-images.githubusercontent.com/11897056/44384715-aab83b00-a54f-11e8-84a1-5e04392602f5.png)

**Comment by HDB-Li** [comment]
I see.  I had never test gif.  Thanks.  😆

**Comment by zou145688zhuang** [comment]
![1](https://user-images.githubusercontent.com/11897056/44387169-629d1680-a557-11e8-9b62-f223d6254ca8.png)
当字符串过长，我现在文字大概超过800行，此时的UILable显示空白，我现在使用UITextView进行加载，通过约束最大显示高度，来显示文字。应该是lable对过长的文字渲染不出来，通过textview分段显示滚动。

**Comment by zou145688zhuang** [comment]
这个工具既然是debug调试工具，我觉得是不是只需要在debug模式下执行，不需要通过pod来配置，直接在代码里- (void)startWorking{
    #if DEBUG
    if (!_isWorking) {
        _isWorking = YES;
        // Open crash helper
        [[LLCrashHelper sharedHelper] setEnable:YES];
        // Open log helper
        [[LLLogHelper sharedHelper] setEnable:YES];
        // Open network monitoring
        [[LLNetworkHelper sharedHelper] setEnable:YES];
        // Open app monitoring
        [[LLAppHelper sharedHelper] startMonitoring];
        // Open screenshot
        [[LLScreenshotHelper sharedHelper] setEnable:YES];
        // show window
        [self.window showWindow];
    }
     #endif
}

**Comment by HDB-Li** [comment]
@zou145688zhuang  
you can write this in your podfile .`pod 'LLDebugTool' , '~> 1.0.0' ,:configurations => ['Debug']`.

Use `configurations => ['Debug']` means it will only work in Debug environment.

**Comment by zou145688zhuang** [comment]
![2018-08-21 4 08 20](https://user-images.githubusercontent.com/11897056/44389132-a0e90480-a55c-11e8-940b-ae73c2ed5cad.png)   多次崩溃在这里

**Comment by HDB-Li** [comment]
@zou145688zhuang
