### ISSUE TITLE
截屏功能是否可以做开关

### ISSUE THREAD

**Issue by JDongKhan** [HDB-Li/LLDebugTool#28]
我们截屏有自己的功能，所以需要屏蔽掉工具里面的截屏功能

还有LL_Swizzling.h里面根据isWorking判断是否可以改成根据LLNetworkHelper的enable，外面关不掉这个功能。

因为这个模块影响了我们大部分接口请求失败，并且上传文件也不行，奇怪的是一部分接口是没问题，所以我猜测是不是某些 设置部分服务器不支持。

**Comment by HDB-Li** [comment]
Of course. I will release a version tomorrow.

**Comment by JDongKhan** [comment]
还有日志详情里面的contentLabel（其实是textView）在iPhone5 8.1下字体是黑色的

**Comment by JDongKhan** [comment]
还有当response Body 文本过长不会滚动！

**Comment by HDB-Li** [comment]
NSLayoutConstraint works different in ios8 and ios11.  I will use observe frame to control scrollable.
