### ISSUE TITLE
Using LLog in swift

### ISSUE THREAD

**Issue by pikachu987** [HDB-Li/LLDebugTool#30]
Hi I tried to use LLog on Swift4.
However, the LLog was declared as #define and could not be used.
![2018-08-30 6 14 04](https://user-images.githubusercontent.com/16880502/44842369-9aefd380-ac80-11e8-820c-71469388cdde.png)

So I tried to use LLog by creating a .h, .m file
Implicit declaration of function 'LLog' is invalid in C99
I got this error.
![2018-08-30 6 13 44](https://user-images.githubusercontent.com/16880502/44842350-8f041180-ac80-11e8-8cdf-daeb2fbe5995.png)

Please support LLog in swift4
thank you.

**Comment by pikachu987** [comment]
Can you make a func to replace LLog when trying to write LLog in Swift?

**Comment by HDB-Li** [comment]
I will release a version used in swift today. 😆  @pikachu987

**Comment by pikachu987** [comment]
Thanks to you, I have used a very good library.
