### ISSUE TITLE
UIAlertView 之后 对loading造成影响了

### ISSUE THREAD

**Issue by datafu** [HDB-Li/LLDebugTool#45]
我弹出一个alertview之后 ，然后     UIWindow *keyWindow = [UIApplication sharedApplication].keyWindow;--》这个keywindow 显示为LLWindow ，然后[MBProgressHUD showHUDAddedTo:view animated:YES] ，发现loading 只在小圆点里面loading  这个要怎么解决？

**Comment by HDB-Li** [comment]
@datafu  Maybe it is a bug. I will reopen it and fix it. It would be better if you could provide some means of reproduction!

**Comment by HDB-Li** [comment]
@datafu 

You can add this method in `LLWindow.m` to fix your problem, but it's not the best solution, I did not reproduce it, Could you tell me how to reproduct it? I will try to fix next time.

```
- (void)becomeKeyWindow {
    [super becomeKeyWindow];
    [[UIApplication sharedApplication].delegate.window makeKeyWindow];
}
```
