### ISSUE TITLE
支持上线Appstore吗？

### ISSUE THREAD

**Issue by josercc** [HDB-Li/LLDebugTool#5]
我们目前用的调试工具是 FLEX 但是不能上线
我们想上线也可以让用户发送我们一些日志 做隐藏入口
不知道这个库支持上线 AppStore 吗

**Comment by HDB-Li** [comment]
理论上是支持的，但是不建议你用这个库去上线。还不足够稳定，以后会考虑把日志功能单独抽离出来，专门用于线上日志埋点。Thanks 😄

**Comment by crespoxiao** [comment]
@josercc  - (NSString *)networkingStatesFromStatebar  用了私有 api ，其他地方我还没看，最好只在 debug 下使用。

**Comment by josercc** [comment]
Thanks 我们需要找个可以上线 遇到问题可以提供一些信息的库 暂时没发现类似 FLEX 库的


原始邮件
发件人:Chengfei Xiaonotifications@github.com
收件人:HDB-Li/LLDebugToolLLDebugTool@noreply.github.com
抄送:君赏josercc@163.com; Mentionmention@noreply.github.com
发送时间:2018年5月30日(周三) 10:42
主题:Re: [HDB-Li/LLDebugTool] 支持上线Appstore吗？ (#5)


@josercc - (NSString *)networkingStatesFromStatebar 用了私有 api ，其他地方我还没看，最好只在 debug 下使用。

**Comment by HDB-Li** [comment]
networkingStatesFromStatebar 这个方法我目前线上的项目有用到这个方法，可以正常过审核。 @josercc
