### ISSUE TITLE
No visible @interface for 'FMResultSet' declares the selector 'objectForColumn:'

### ISSUE THREAD

**Issue by BurapaLi** [HDB-Li/LLDebugTool#53]

**Comment by HDB-Li** [comment]
Hi @BurapaLi , Can you provide additional information?

ps: Is your version of FMDB the latest version?

**Comment by BurapaLi** [comment]
After adding the method that changes can

**Comment by HDB-Li** [comment]
`No visible @interface for 'FMResultSet' declares the selector 'objectForColumn:'` means `FMResultSet` defined the interface, but method isn't implemented.  My guess is that this is a problem with the `FMDB` library in your code.

**Comment by BurapaLi** [comment]
In the new version of FMDB, objectForColumn is replaced with a method, which cannot be found, and is resolved by adding it

**Comment by HDB-Li** [comment]
What's your FMDB version?

**Comment by BurapaLi** [comment]
2.6.2

**Comment by HDB-Li** [comment]
Try the latest release version 2.7.5
