### ISSUE TITLE
Parse error: invalid GitHub repository identifier "LLDebugToolSwift"

### ISSUE THREAD

**Issue by Hanrovey** [HDB-Li/LLDebugTool#54]
Cartfile中：
github "LLDebugToolSwift"

使用Carthage update --platform iOS

提示报错：Parse error: invalid GitHub repository identifier "LLDebugToolSwift"

**Comment by HDB-Li** [comment]
Maybe I made a mistake and tried using cocoapods or importing the source code directly. I'll fix that in the next release. @Hanrovey
