### ISSUE TITLE
my app don‘t show tabbar

### ISSUE THREAD

**Issue by didiaodanding** [HDB-Li/LLDebugTool#55]

**Comment by HDB-Li** [comment]
Can you provide more information？ @didiaodanding

**Comment by didiaodanding** [comment]
I found the reason of this probleam , because addSubview implementation of uitabbar category. just like this:
@implementation UITabBar (Custom)
- (void)addSubview:(UIView *)view
{
    if (view.tag != TABBARVIEW_TAG) {
        return;
    }
    
    [super addSubview:view];
}

**Comment by HDB-Li** [comment]
Okey : )
