### ISSUE TITLE
能添加按页面列出网络请求吗? 而不是filter,希望能把入参单独拿出来

### ISSUE THREAD

**Issue by WellSimith** [HDB-Li/LLDebugTool#59]
希望加入考虑

**Comment by WellSimith** [comment]
网络请求按页面缓存, 按页面获取

**Comment by HDB-Li** [comment]
@WellSimith  According to viewController?

**Comment by WellSimith** [comment]
Yes, just like Log page, can u do it?

**Comment by HDB-Li** [comment]
@WellSimith  Network requests cannot be located to a specific viewController because network requests are detected by registering custom `URLProtocol` and there is no way to know which viewController you are calling the request from.

**Comment by WellSimith** [comment]
I know, THKS!
