### ISSUE TITLE
旧项目中使用的ASIHTTPRequest无法检测到网络请求

### ISSUE THREAD

**Issue by zllbird** [HDB-Li/LLDebugTool#6]
使用中，新项目使用AFN能检测到网络请求，但旧项目中使用的ASIHTTPRequest没有监测到

**Comment by HDB-Li** [comment]
ASI的底层是封装的CFNetwork的C函数， AFN封装的是NSURLSession和NSURLConnection，所以没有办法检测到ASI的网络请求。
