### ISSUE TITLE
FMResultSet的objectForColumn找不到

### ISSUE THREAD

**Issue by ChoiKarl** [HDB-Li/LLDebugTool#63]
我们项目用的FMDB还是2.6.2，所有没有这个方法。

**Comment by HDB-Li** [comment]
Maybe you can update your 'FMDB'. Instead of rewriting the database function, I used FMDB directly. @ChoiKarl

**Comment by HDB-Li** [comment]
I will try the version 2.6.2 of `FMDB`, If it doesn't affect my changes too much

**Comment by ChoiKarl** [comment]
> I will try the version 2.6.2 of `FMDB`, If it doesn't affect my changes too much

`FMDB`2.6.2有`objectForColumnName:`这么一个方法，或许你可以用`respondsToSelector`和`performSelector`去判断和调用，我尝试在pod里修改了你的代码，是可行的。

**Comment by HDB-Li** [comment]
I will fix it this afternoon.
