### ISSUE TITLE
用XCode11.2点击network列表必闪退，希望能修复一下

### ISSUE THREAD

**Issue by sinsen** [HDB-Li/LLDebugTool#76]
用XCode11.2点击network列表必闪退，希望能尽快修复一下

**Comment by HDB-Li** [comment]
Thanks, Today later or tomorrow.

**Comment by HDB-Li** [comment]
@sinsen Hi,  Could you send your crash info to me? I just tried on XCode 11.2, Mac OS 10.15.1.  Nothing crashed.

**Comment by sinsen** [comment]
更新1.3.4版本之后貌似ok了，之前用1.2.2版本的会



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HDB-Li"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午5:37
收件人: "HDB-Li/LLDebugTool"<LLDebugTool@noreply.github.com&gt;; 
抄送: "存"<626524760@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [HDB-Li/LLDebugTool] 用XCode11.2点击network列表必闪退，希望能修复一下 (#76)




@sinsen Hi,  Could you send your crash info to me? I just tried on XCode 11.2, Mac OS 10.15.1.  Nothing crashed.

**Comment by HDB-Li** [comment]
Ok.
