### ISSUE TITLE
同时接了极光推送，启动会偶尔崩溃

### ISSUE THREAD

**Issue by whichpage** [HDB-Li/LLDebugTool#84]

**Comment by HDB-Li** [comment]
@whichpage  Hi, Could you provide more informations? such as crash reason and crash stack.

**Comment by whichpage** [comment]
![AB10EE61-AADE-4B45-940C-BCB5BEA9F998](https://user-images.githubusercontent.com/20877763/71506828-70864880-28bd-11ea-9720-d1bae287c4b8.png)
<img width="1288" alt="QQ20191227-152732@2x" src="https://user-images.githubusercontent.com/20877763/71506837-767c2980-28bd-11ea-80ba-e79c71d08156.png">
具体原因我再找下 目前项目同时接入的话很高几率崩溃 但是我写了个demo没法复现

**Comment by whichpage** [comment]
目前在8p 12.3.1 还有个SE 上出现；7p 13， xs 13的系统没问题

**Comment by HDB-Li** [comment]
@whichpage I'm busy these days. If you find out why, I'm looking forward to your telling me. Looks like there was a problem with `CoreLocation`. You can try not use `Mock Location` function. Thanks

**Comment by HDB-Li** [comment]
@whichpage Hi, did you find the reason?

**Comment by whichpage** [comment]
刚试了下 没有再复现
