### ISSUE TITLE
Please remove the CocoaPods ping

### ISSUE THREAD

**Issue by orta** [HDB-Li/LLDebugTool#96]
Hi! 

I think people are shipping this check to production devices and have been the cause of downtime on the CocoaPods website quite a few times. Last year I added code specifically to remove your pod from the website: http://cocoapods.org/pods/LLDebugTool 

I don't think I [can ever remove that code now](https://github.com/CocoaPods/cocoapods.org/commit/5a6c58d91866b7541607176a085fd46cd1062f00), but at least you can remove the check to give our servers a chance to be less busy

![Screen Shot 2020-05-17 at 8 46 50 AM](https://user-images.githubusercontent.com/49038/82148080-2b3cc600-9820-11ea-9289-3d0402787e58.png)

**Comment by freak4pc** [comment]
Adding the offending code for reference: 
https://github.com/HDB-Li/LLDebugTool/commit/ba3c051e9f214a9e3ea4f59b4228641500de9b30#diff-dd97d02d057d55972b9a732bd477aaacR173

**Comment by HDB-Li** [comment]
You can set `autoCheckDebugToolVersion ` to disable this request. Also this check is actually invalid. I can't get the version number correctly. I will remove it later.

**Comment by orta** [comment]
Heh, yeah, I banned your pod page from showing on the CocoaPods website - basically someone shipped your pod to production and we get taken down by their users :D

**Comment by HDB-Li** [comment]
@orta One more question, When I removed this code, Could you cancel banned my pod in future? 

I just wanted to push the new version to the user and add a property to turn it off. I don't think my pod has such a large number of users that would cause DDS attacks on Cocoa pods. So maybe cancel banned my pod in future? 😢

**Comment by Coeur** [comment]
I'm not part of CocoaPods, just a random opinion:
"in the future" could potentially be far away in time depending on the rate of adoption of your new version. So you may better try to get yourself a second pod name (like 'LLDebugTool2' as an example) which doesn't have any release scraping its CocoaPods page, and advertise it around as the replacement of your deprecated pod.

Technically, I believe you can have multiple podspecs files in the same repository, so that both the old pod name and the new one would get updates until a safe version gets largely adopted.

**Comment by orta** [comment]
Yeah, I'm open to removing that code but it's at many requests per-second today. 

It'll take a long time for developers to update your library, then to update their apps, then for users to update their apps. I have no idea when I can undo it though - perhaps once it starts looking like a request a minute or two.

**Comment by HDB-Li** [comment]
@orta I'm removed the CocoaPods ping and release a new version, How long will `LLDebugTool` can be accessed normally in `cocoapods`?

**Comment by orta** [comment]
months, maybe years - depends on how fast people update really.

**Comment by HDB-Li** [comment]
So badly..... Does this affect people's ability to search and install my pod through cocoapods?

**Comment by HDB-Li** [comment]
@orta Is there no other way to solve this problem?

**Comment by orta** [comment]
Nope, not really - to give you some perspective: for every 1 normal website page view we get about 20 pings from this code (see the screenshot above) 

@Coeur's point that you can re-name your library is honestly one of the best ideas

**Comment by HDB-Li** [comment]
@orta  Will this affect when `pod install` or `pod search` my pod?  Renaming is a very bad idea and the worst way. If it doesn't affect `pod install` or `pod search`, the scope of influence should not be particularly large. I can wait until the frequency of this request falls. If `pod install` or `pod search` is affected, I will probably need to rename it.

**For individual developers, the loss of renaming is too great.** 😭

**Comment by freak4pc** [comment]
I believe the code Orta added only blocks your page on the CocoaPods website and not in trunk so install, etc should work. It’s probably easiest to try for yourself on a blank project :)

**Comment by orta** [comment]
Just the web page is blocked, everything else is the same

**Comment by HDB-Li** [comment]
Okey, All I can do is wait.
